name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
 sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get:  ^4.6.6
  geolocator: ^10.1.0 
  dio: ^5.8.0+1  # تحديث لتجنب المشاكل الأمنية
  intl: ^0.20.2  # أحدث إصدار متوافق
  syncfusion_flutter_charts: ^28.2.5+1  # تحديث إلى أحدث إصدار
  lottie: ^3.3.1  # تحديث إلى أحدث إصدار
  geocoding: ^2.2.1
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon-01.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anims/

  fonts:
    - family: flutterfonts
      fonts:
        - asset: assets/fonts/flutterfonts.ttf